{{- if .Values.ingress.enabled -}}
{{- $fullName := include "growthbook.fullname" . -}}
{{- $svcFrontendPort := .Values.service.frontend.port -}}
{{- $svcBackendPort := .Values.service.backend.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "growthbook.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- with .Values.ingress }}
  {{- if or .frontend.tls.enabled .backend.tls.enabled }}
  tls:
    {{- if .frontend.tls.enabled }}
    - hosts:
        - {{ .frontend.host | quote }}
      secretName: {{ .frontend.tls.secretName }}
    {{- end }}
    {{- if .backend.tls.enabled }}
    - hosts:
        - {{ .backend.host | quote }}
      secretName: {{ .backend.tls.secretName }}
    {{- end }}
  {{- end }}
  {{- end }}
  rules:
    {{- with .Values.ingress.frontend }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcFrontendPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcFrontendPort }}
              {{- end }}
      {{- end }}
    {{- with .Values.ingress.backend }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcBackendPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcBackendPort }}
              {{- end }}
      {{- end }}
{{- end }}
