apiVersion: v1
kind: Service
metadata:
  name: {{ include "growthbook.fullname" . }}
  labels:
    {{- include "growthbook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http-frontend
      protocol: TCP
      name: http-frontend
    - port: {{ .Values.service.backend.port }}
      targetPort: http-backend
      protocol: TCP
      name: http-backend
  selector:
    {{- include "growthbook.selectorLabels" . | nindent 4 }}
